server:
  port: 8002

spring:
  application:
    name: cloud-provider-hystrix-payment-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-7001:7001/eureka/,http://eureka-7002:7002/eureka/


