server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务进行路由
      routes:
        - id: paymentHystrixRouth
          uri: lb://cloud-provider-hystrix-payment-service
          predicates:
            - Path=/payment/hystrix/**
        - id: paymentRouth
          uri: lb://cloud-provider-payment-service
          predicates:
            - Path=/payment/**
        # 访问http://localhost:9527/guonei，将到百度新闻
        - id: guoneiRouth
          uri: http://news.baidu.com/guonei
          predicates:
            - Path=/guonei

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-7001:7001/eureka/,http://eureka-7002:7002/eureka/
