server:
  port: 6005
spring:
  application:
    name: cloud-alibaba-consumer-sentinel-order
  cloud:
    nacos:
      discovery:
        server-addr: http://119.29.165.98:8848 #Nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard地址
        # 应用与sentinel交互的默认端口是8719，如果该端口被占用则会自动+1 变成 8720 ，直到找到未被占用的端口
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: '*'
