server:
  port: 9002
spring:
  application:
    name: cloud-alibaba-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: http://119.29.165.98:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"