server:
  port: 2002

spring:
  application:
    name: seata-storage-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.29.165.98:3306/seata_storage?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: "@Cj19861127"
  cloud:
    nacos:
      discovery:
        server-addr: http://119.29.165.98:8848

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entities
  configuration:
    map-underscore-to-camel-case: true

feign:
  hystrix:
    enabled: true

seata:
  application-id: ${spring.application.name}
  tx-service-group: my_test_tx_group
  service:
    grouplist:
      default: 127.0.0.1:8091
    vgroup-mapping:
      my_test_tx_group: default
  enabled: true
  config:
    type: nacos
    nacos:
      namespace:
      server-addr: 119.29.165.98:8848
      group: SEATA_GROUP
      username: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 119.29.165.98:8848
      group: SEATA_GROUP
      namespace:
      userName: "nacos"
      password: "nacos"