server:
  port: 8802
spring:
  application:
    name: cloud-stream-rabbitmq-consumer
  cloud:
    stream:
      binders: # 这是一组binder的集合，这里配置了一个名为defaultRabbit的binder
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
        input: # 输入通道
          destination: test.rabbitmq.cloud
          content-type: application/json
          default-binder: defaultRabbit
          group: consumer
eureka:
  client:
    service-url:
      defaultZone: http://eureka-7001:7001/eureka/,http://eureka-7002:7002/eureka/
  instance:
    prefer-ip-address: true
    instance-id: receive-8802.com